// ----------------------------------------------------------------------------
// File: Metadata.proto
// Author: Branko Blagojevic <branko.blagojevic@comtrade.com>
// ----------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: Metadata.proto

package go_eosgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TYPE int32

const (
	TYPE_FILE      TYPE = 0
	TYPE_CONTAINER TYPE = 1
	TYPE_LISTING   TYPE = 2
)

// Enum value maps for TYPE.
var (
	TYPE_name = map[int32]string{
		0: "FILE",
		1: "CONTAINER",
		2: "LISTING",
	}
	TYPE_value = map[string]int32{
		"FILE":      0,
		"CONTAINER": 1,
		"LISTING":   2,
	}
)

func (x TYPE) Enum() *TYPE {
	p := new(TYPE)
	*p = x
	return p
}

func (x TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_Metadata_proto_enumTypes[0].Descriptor()
}

func (TYPE) Type() protoreflect.EnumType {
	return &file_Metadata_proto_enumTypes[0]
}

func (x TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYPE.Descriptor instead.
func (TYPE) EnumDescriptor() ([]byte, []int) {
	return file_Metadata_proto_rawDescGZIP(), []int{0}
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path []byte `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id   uint64 `protobuf:"fixed64,2,opt,name=id,proto3" json:"id,omitempty"`
	Ino  uint64 `protobuf:"fixed64,3,opt,name=ino,proto3" json:"ino,omitempty"`
	Type TYPE   `protobuf:"varint,4,opt,name=type,proto3,enum=eos.console.TYPE" json:"type,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_Metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_Metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Metadata) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Metadata) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *Metadata) GetType() TYPE {
	if x != nil {
		return x.Type
	}
	return TYPE_FILE
}

var File_Metadata_proto protoreflect.FileDescriptor

var file_Metadata_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x22, 0x67, 0x0a,
	0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x03, 0x69, 0x6e, 0x6f, 0x12,
	0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x2c, 0x0a, 0x04, 0x54, 0x59, 0x50, 0x45, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x54,
	0x41, 0x49, 0x4e, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x49, 0x53, 0x54, 0x49,
	0x4e, 0x47, 0x10, 0x02, 0x42, 0x8d, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x6f, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x42, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x72, 0x6e, 0x2d, 0x65, 0x6f, 0x73, 0x2f, 0x67,
	0x6f, 0x2d, 0x65, 0x6f, 0x73, 0x67, 0x72, 0x70, 0x63, 0xa2, 0x02, 0x03, 0x45, 0x43, 0x58, 0xaa,
	0x02, 0x0b, 0x45, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0xca, 0x02, 0x0b,
	0x45, 0x6f, 0x73, 0x5c, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0xe2, 0x02, 0x17, 0x45, 0x6f,
	0x73, 0x5c, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x45, 0x6f, 0x73, 0x3a, 0x3a, 0x43, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Metadata_proto_rawDescOnce sync.Once
	file_Metadata_proto_rawDescData = file_Metadata_proto_rawDesc
)

func file_Metadata_proto_rawDescGZIP() []byte {
	file_Metadata_proto_rawDescOnce.Do(func() {
		file_Metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_Metadata_proto_rawDescData)
	})
	return file_Metadata_proto_rawDescData
}

var file_Metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Metadata_proto_goTypes = []interface{}{
	(TYPE)(0),        // 0: eos.console.TYPE
	(*Metadata)(nil), // 1: eos.console.Metadata
}
var file_Metadata_proto_depIdxs = []int32{
	0, // 0: eos.console.Metadata.type:type_name -> eos.console.TYPE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Metadata_proto_init() }
func file_Metadata_proto_init() {
	if File_Metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Metadata_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Metadata_proto_goTypes,
		DependencyIndexes: file_Metadata_proto_depIdxs,
		EnumInfos:         file_Metadata_proto_enumTypes,
		MessageInfos:      file_Metadata_proto_msgTypes,
	}.Build()
	File_Metadata_proto = out.File
	file_Metadata_proto_rawDesc = nil
	file_Metadata_proto_goTypes = nil
	file_Metadata_proto_depIdxs = nil
}
