// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: Recycle.proto

package go_eosgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecycleProto_RecycleType int32

const (
	RecycleProto_UID RecycleProto_RecycleType = 0
	RecycleProto_RID RecycleProto_RecycleType = 1
	RecycleProto_ALL RecycleProto_RecycleType = 2
)

// Enum value maps for RecycleProto_RecycleType.
var (
	RecycleProto_RecycleType_name = map[int32]string{
		0: "UID",
		1: "RID",
		2: "ALL",
	}
	RecycleProto_RecycleType_value = map[string]int32{
		"UID": 0,
		"RID": 1,
		"ALL": 2,
	}
)

func (x RecycleProto_RecycleType) Enum() *RecycleProto_RecycleType {
	p := new(RecycleProto_RecycleType)
	*p = x
	return p
}

func (x RecycleProto_RecycleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecycleProto_RecycleType) Descriptor() protoreflect.EnumDescriptor {
	return file_Recycle_proto_enumTypes[0].Descriptor()
}

func (RecycleProto_RecycleType) Type() protoreflect.EnumType {
	return &file_Recycle_proto_enumTypes[0]
}

func (x RecycleProto_RecycleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecycleProto_RecycleType.Descriptor instead.
func (RecycleProto_RecycleType) EnumDescriptor() ([]byte, []int) {
	return file_Recycle_proto_rawDescGZIP(), []int{0, 0}
}

type RecycleProto_ConfigProto_OpType int32

const (
	RecycleProto_ConfigProto_ADD_BIN          RecycleProto_ConfigProto_OpType = 0
	RecycleProto_ConfigProto_RM_BIN           RecycleProto_ConfigProto_OpType = 1
	RecycleProto_ConfigProto_LIFETIME         RecycleProto_ConfigProto_OpType = 2
	RecycleProto_ConfigProto_RATIO            RecycleProto_ConfigProto_OpType = 3
	RecycleProto_ConfigProto_SIZE             RecycleProto_ConfigProto_OpType = 4
	RecycleProto_ConfigProto_INODES           RecycleProto_ConfigProto_OpType = 5
	RecycleProto_ConfigProto_POLL_INTERVAL    RecycleProto_ConfigProto_OpType = 6
	RecycleProto_ConfigProto_COLLECT_INTERVAL RecycleProto_ConfigProto_OpType = 7
	RecycleProto_ConfigProto_REMOVE_INTERVAL  RecycleProto_ConfigProto_OpType = 8
	RecycleProto_ConfigProto_DRY_RUN          RecycleProto_ConfigProto_OpType = 9
	RecycleProto_ConfigProto_DUMP             RecycleProto_ConfigProto_OpType = 10
	RecycleProto_ConfigProto_ENABLE           RecycleProto_ConfigProto_OpType = 11
)

// Enum value maps for RecycleProto_ConfigProto_OpType.
var (
	RecycleProto_ConfigProto_OpType_name = map[int32]string{
		0:  "ADD_BIN",
		1:  "RM_BIN",
		2:  "LIFETIME",
		3:  "RATIO",
		4:  "SIZE",
		5:  "INODES",
		6:  "POLL_INTERVAL",
		7:  "COLLECT_INTERVAL",
		8:  "REMOVE_INTERVAL",
		9:  "DRY_RUN",
		10: "DUMP",
		11: "ENABLE",
	}
	RecycleProto_ConfigProto_OpType_value = map[string]int32{
		"ADD_BIN":          0,
		"RM_BIN":           1,
		"LIFETIME":         2,
		"RATIO":            3,
		"SIZE":             4,
		"INODES":           5,
		"POLL_INTERVAL":    6,
		"COLLECT_INTERVAL": 7,
		"REMOVE_INTERVAL":  8,
		"DRY_RUN":          9,
		"DUMP":             10,
		"ENABLE":           11,
	}
)

func (x RecycleProto_ConfigProto_OpType) Enum() *RecycleProto_ConfigProto_OpType {
	p := new(RecycleProto_ConfigProto_OpType)
	*p = x
	return p
}

func (x RecycleProto_ConfigProto_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecycleProto_ConfigProto_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_Recycle_proto_enumTypes[1].Descriptor()
}

func (RecycleProto_ConfigProto_OpType) Type() protoreflect.EnumType {
	return &file_Recycle_proto_enumTypes[1]
}

func (x RecycleProto_ConfigProto_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecycleProto_ConfigProto_OpType.Descriptor instead.
func (RecycleProto_ConfigProto_OpType) EnumDescriptor() ([]byte, []int) {
	return file_Recycle_proto_rawDescGZIP(), []int{0, 3, 0}
}

type RecycleProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Subcmd:
	//
	//	*RecycleProto_Ls
	//	*RecycleProto_Purge
	//	*RecycleProto_Restore
	//	*RecycleProto_Config
	//	*RecycleProto_Project
	Subcmd isRecycleProto_Subcmd `protobuf_oneof:"subcmd"`
}

func (x *RecycleProto) Reset() {
	*x = RecycleProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recycle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecycleProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleProto) ProtoMessage() {}

func (x *RecycleProto) ProtoReflect() protoreflect.Message {
	mi := &file_Recycle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleProto.ProtoReflect.Descriptor instead.
func (*RecycleProto) Descriptor() ([]byte, []int) {
	return file_Recycle_proto_rawDescGZIP(), []int{0}
}

func (m *RecycleProto) GetSubcmd() isRecycleProto_Subcmd {
	if m != nil {
		return m.Subcmd
	}
	return nil
}

func (x *RecycleProto) GetLs() *RecycleProto_LsProto {
	if x, ok := x.GetSubcmd().(*RecycleProto_Ls); ok {
		return x.Ls
	}
	return nil
}

func (x *RecycleProto) GetPurge() *RecycleProto_PurgeProto {
	if x, ok := x.GetSubcmd().(*RecycleProto_Purge); ok {
		return x.Purge
	}
	return nil
}

func (x *RecycleProto) GetRestore() *RecycleProto_RestoreProto {
	if x, ok := x.GetSubcmd().(*RecycleProto_Restore); ok {
		return x.Restore
	}
	return nil
}

func (x *RecycleProto) GetConfig() *RecycleProto_ConfigProto {
	if x, ok := x.GetSubcmd().(*RecycleProto_Config); ok {
		return x.Config
	}
	return nil
}

func (x *RecycleProto) GetProject() *RecycleProto_ProjectProto {
	if x, ok := x.GetSubcmd().(*RecycleProto_Project); ok {
		return x.Project
	}
	return nil
}

type isRecycleProto_Subcmd interface {
	isRecycleProto_Subcmd()
}

type RecycleProto_Ls struct {
	Ls *RecycleProto_LsProto `protobuf:"bytes,1,opt,name=ls,proto3,oneof"`
}

type RecycleProto_Purge struct {
	Purge *RecycleProto_PurgeProto `protobuf:"bytes,2,opt,name=purge,proto3,oneof"`
}

type RecycleProto_Restore struct {
	Restore *RecycleProto_RestoreProto `protobuf:"bytes,3,opt,name=restore,proto3,oneof"`
}

type RecycleProto_Config struct {
	Config *RecycleProto_ConfigProto `protobuf:"bytes,4,opt,name=config,proto3,oneof"`
}

type RecycleProto_Project struct {
	Project *RecycleProto_ProjectProto `protobuf:"bytes,5,opt,name=project,proto3,oneof"`
}

func (*RecycleProto_Ls) isRecycleProto_Subcmd() {}

func (*RecycleProto_Purge) isRecycleProto_Subcmd() {}

func (*RecycleProto_Restore) isRecycleProto_Subcmd() {}

func (*RecycleProto_Config) isRecycleProto_Subcmd() {}

func (*RecycleProto_Project) isRecycleProto_Subcmd() {}

type RecycleProto_LsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullDetails bool                     `protobuf:"varint,1,opt,name=FullDetails,proto3" json:"FullDetails,omitempty"`
	NumericIds  bool                     `protobuf:"varint,2,opt,name=NumericIds,proto3" json:"NumericIds,omitempty"`
	MonitorFmt  bool                     `protobuf:"varint,3,opt,name=MonitorFmt,proto3" json:"MonitorFmt,omitempty"`
	Date        string                   `protobuf:"bytes,4,opt,name=Date,proto3" json:"Date,omitempty"`
	Maxentries  int32                    `protobuf:"varint,5,opt,name=Maxentries,proto3" json:"Maxentries,omitempty"`
	Type        RecycleProto_RecycleType `protobuf:"varint,6,opt,name=Type,proto3,enum=eos.console.RecycleProto_RecycleType" json:"Type,omitempty"`
	RecycleId   string                   `protobuf:"bytes,7,opt,name=RecycleId,proto3" json:"RecycleId,omitempty"`
}

func (x *RecycleProto_LsProto) Reset() {
	*x = RecycleProto_LsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recycle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecycleProto_LsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleProto_LsProto) ProtoMessage() {}

func (x *RecycleProto_LsProto) ProtoReflect() protoreflect.Message {
	mi := &file_Recycle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleProto_LsProto.ProtoReflect.Descriptor instead.
func (*RecycleProto_LsProto) Descriptor() ([]byte, []int) {
	return file_Recycle_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RecycleProto_LsProto) GetFullDetails() bool {
	if x != nil {
		return x.FullDetails
	}
	return false
}

func (x *RecycleProto_LsProto) GetNumericIds() bool {
	if x != nil {
		return x.NumericIds
	}
	return false
}

func (x *RecycleProto_LsProto) GetMonitorFmt() bool {
	if x != nil {
		return x.MonitorFmt
	}
	return false
}

func (x *RecycleProto_LsProto) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RecycleProto_LsProto) GetMaxentries() int32 {
	if x != nil {
		return x.Maxentries
	}
	return 0
}

func (x *RecycleProto_LsProto) GetType() RecycleProto_RecycleType {
	if x != nil {
		return x.Type
	}
	return RecycleProto_UID
}

func (x *RecycleProto_LsProto) GetRecycleId() string {
	if x != nil {
		return x.RecycleId
	}
	return ""
}

type RecycleProto_PurgeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date      string                   `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Key       string                   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Type      RecycleProto_RecycleType `protobuf:"varint,3,opt,name=Type,proto3,enum=eos.console.RecycleProto_RecycleType" json:"Type,omitempty"`
	RecycleId string                   `protobuf:"bytes,4,opt,name=RecycleId,proto3" json:"RecycleId,omitempty"`
}

func (x *RecycleProto_PurgeProto) Reset() {
	*x = RecycleProto_PurgeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recycle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecycleProto_PurgeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleProto_PurgeProto) ProtoMessage() {}

func (x *RecycleProto_PurgeProto) ProtoReflect() protoreflect.Message {
	mi := &file_Recycle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleProto_PurgeProto.ProtoReflect.Descriptor instead.
func (*RecycleProto_PurgeProto) Descriptor() ([]byte, []int) {
	return file_Recycle_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RecycleProto_PurgeProto) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RecycleProto_PurgeProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RecycleProto_PurgeProto) GetType() RecycleProto_RecycleType {
	if x != nil {
		return x.Type
	}
	return RecycleProto_UID
}

func (x *RecycleProto_PurgeProto) GetRecycleId() string {
	if x != nil {
		return x.RecycleId
	}
	return ""
}

type RecycleProto_RestoreProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForceOrigName   bool   `protobuf:"varint,1,opt,name=ForceOrigName,proto3" json:"ForceOrigName,omitempty"`
	RestoreVersions bool   `protobuf:"varint,2,opt,name=RestoreVersions,proto3" json:"RestoreVersions,omitempty"`
	MakePath        bool   `protobuf:"varint,3,opt,name=MakePath,proto3" json:"MakePath,omitempty"`
	Key             string `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *RecycleProto_RestoreProto) Reset() {
	*x = RecycleProto_RestoreProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recycle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecycleProto_RestoreProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleProto_RestoreProto) ProtoMessage() {}

func (x *RecycleProto_RestoreProto) ProtoReflect() protoreflect.Message {
	mi := &file_Recycle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleProto_RestoreProto.ProtoReflect.Descriptor instead.
func (*RecycleProto_RestoreProto) Descriptor() ([]byte, []int) {
	return file_Recycle_proto_rawDescGZIP(), []int{0, 2}
}

func (x *RecycleProto_RestoreProto) GetForceOrigName() bool {
	if x != nil {
		return x.ForceOrigName
	}
	return false
}

func (x *RecycleProto_RestoreProto) GetRestoreVersions() bool {
	if x != nil {
		return x.RestoreVersions
	}
	return false
}

func (x *RecycleProto_RestoreProto) GetMakePath() bool {
	if x != nil {
		return x.MakePath
	}
	return false
}

func (x *RecycleProto_RestoreProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RecycleProto_ConfigProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op          RecycleProto_ConfigProto_OpType `protobuf:"varint,1,opt,name=op,proto3,enum=eos.console.RecycleProto_ConfigProto_OpType" json:"op,omitempty"`
	Subtree     string                          `protobuf:"bytes,2,opt,name=Subtree,proto3" json:"Subtree,omitempty"`
	LifetimeSec int32                           `protobuf:"varint,3,opt,name=LifetimeSec,proto3" json:"LifetimeSec,omitempty"`
	Ratio       float32                         `protobuf:"fixed32,4,opt,name=Ratio,proto3" json:"Ratio,omitempty"`
	Size        uint64                          `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"` // Use by either SIZE or INODES
	Value       string                          `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RecycleProto_ConfigProto) Reset() {
	*x = RecycleProto_ConfigProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recycle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecycleProto_ConfigProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleProto_ConfigProto) ProtoMessage() {}

func (x *RecycleProto_ConfigProto) ProtoReflect() protoreflect.Message {
	mi := &file_Recycle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleProto_ConfigProto.ProtoReflect.Descriptor instead.
func (*RecycleProto_ConfigProto) Descriptor() ([]byte, []int) {
	return file_Recycle_proto_rawDescGZIP(), []int{0, 3}
}

func (x *RecycleProto_ConfigProto) GetOp() RecycleProto_ConfigProto_OpType {
	if x != nil {
		return x.Op
	}
	return RecycleProto_ConfigProto_ADD_BIN
}

func (x *RecycleProto_ConfigProto) GetSubtree() string {
	if x != nil {
		return x.Subtree
	}
	return ""
}

func (x *RecycleProto_ConfigProto) GetLifetimeSec() int32 {
	if x != nil {
		return x.LifetimeSec
	}
	return 0
}

func (x *RecycleProto_ConfigProto) GetRatio() float32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *RecycleProto_ConfigProto) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RecycleProto_ConfigProto) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RecycleProto_ProjectProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Acl  string `protobuf:"bytes,2,opt,name=acl,proto3" json:"acl,omitempty"`
}

func (x *RecycleProto_ProjectProto) Reset() {
	*x = RecycleProto_ProjectProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recycle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecycleProto_ProjectProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleProto_ProjectProto) ProtoMessage() {}

func (x *RecycleProto_ProjectProto) ProtoReflect() protoreflect.Message {
	mi := &file_Recycle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleProto_ProjectProto.ProtoReflect.Descriptor instead.
func (*RecycleProto_ProjectProto) Descriptor() ([]byte, []int) {
	return file_Recycle_proto_rawDescGZIP(), []int{0, 4}
}

func (x *RecycleProto_ProjectProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RecycleProto_ProjectProto) GetAcl() string {
	if x != nil {
		return x.Acl
	}
	return ""
}

var File_Recycle_proto protoreflect.FileDescriptor

var file_Recycle_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x22, 0xca, 0x0a, 0x0a,
	0x0c, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x33, 0x0a,
	0x02, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x65, 0x6f, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x02,
	0x6c, 0x73, 0x12, 0x3c, 0x0a, 0x05, 0x70, 0x75, 0x72, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e,
	0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x72,
	0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x70, 0x75, 0x72, 0x67, 0x65,
	0x12, 0x42, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e,
	0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x42, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0xf8, 0x01, 0x0a, 0x07, 0x4c, 0x73,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x46, 0x75, 0x6c, 0x6c,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x75, 0x6d, 0x65, 0x72,
	0x69, 0x63, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x4e, 0x75, 0x6d,
	0x65, 0x72, 0x69, 0x63, 0x49, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x46, 0x6d, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x4d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x46, 0x6d, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4d,
	0x61, 0x78, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x4d, 0x61, 0x78, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x65, 0x6f, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x49, 0x64, 0x1a, 0x8b, 0x01, 0x0a, 0x0a, 0x50, 0x75, 0x72, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x39, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x49, 0x64, 0x1a, 0x8c, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4f, 0x72, 0x69, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x46, 0x6f, 0x72, 0x63,
	0x65, 0x4f, 0x72, 0x69, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0f, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x6b, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x4d, 0x61, 0x6b, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65,
	0x79, 0x1a, 0xfb, 0x02, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x3c, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e,
	0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x6f, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x69, 0x66,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x52,
	0x61, 0x74, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x52, 0x61, 0x74, 0x69,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x06,
	0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x44, 0x44, 0x5f, 0x42, 0x49,
	0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x4d, 0x5f, 0x42, 0x49, 0x4e, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x4c, 0x49, 0x46, 0x45, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x49, 0x5a, 0x45,
	0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x4f, 0x44, 0x45, 0x53, 0x10, 0x05, 0x12, 0x11,
	0x0a, 0x0d, 0x50, 0x4f, 0x4c, 0x4c, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x56, 0x41, 0x4c, 0x10,
	0x06, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x5f, 0x49, 0x4e, 0x54,
	0x45, 0x52, 0x56, 0x41, 0x4c, 0x10, 0x07, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x4d, 0x4f, 0x56,
	0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x56, 0x41, 0x4c, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x52, 0x59, 0x5f, 0x52, 0x55, 0x4e, 0x10, 0x09, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x55, 0x4d,
	0x50, 0x10, 0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x0b, 0x1a,
	0x34, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x63, 0x6c, 0x22, 0x28, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x52, 0x49, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x42,
	0x08, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x63, 0x6d, 0x64, 0x42, 0x8c, 0x01, 0x0a, 0x0f, 0x63, 0x6f,
	0x6d, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x42, 0x0c, 0x52,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x72, 0x6e, 0x2d, 0x65,
	0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x6f, 0x73, 0x67, 0x72, 0x70, 0x63, 0xa2, 0x02, 0x03,
	0x45, 0x43, 0x58, 0xaa, 0x02, 0x0b, 0x45, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0xca, 0x02, 0x0b, 0x45, 0x6f, 0x73, 0x5c, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0xe2,
	0x02, 0x17, 0x45, 0x6f, 0x73, 0x5c, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x45, 0x6f, 0x73, 0x3a,
	0x3a, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Recycle_proto_rawDescOnce sync.Once
	file_Recycle_proto_rawDescData = file_Recycle_proto_rawDesc
)

func file_Recycle_proto_rawDescGZIP() []byte {
	file_Recycle_proto_rawDescOnce.Do(func() {
		file_Recycle_proto_rawDescData = protoimpl.X.CompressGZIP(file_Recycle_proto_rawDescData)
	})
	return file_Recycle_proto_rawDescData
}

var file_Recycle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Recycle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Recycle_proto_goTypes = []interface{}{
	(RecycleProto_RecycleType)(0),        // 0: eos.console.RecycleProto.RecycleType
	(RecycleProto_ConfigProto_OpType)(0), // 1: eos.console.RecycleProto.ConfigProto.OpType
	(*RecycleProto)(nil),                 // 2: eos.console.RecycleProto
	(*RecycleProto_LsProto)(nil),         // 3: eos.console.RecycleProto.LsProto
	(*RecycleProto_PurgeProto)(nil),      // 4: eos.console.RecycleProto.PurgeProto
	(*RecycleProto_RestoreProto)(nil),    // 5: eos.console.RecycleProto.RestoreProto
	(*RecycleProto_ConfigProto)(nil),     // 6: eos.console.RecycleProto.ConfigProto
	(*RecycleProto_ProjectProto)(nil),    // 7: eos.console.RecycleProto.ProjectProto
}
var file_Recycle_proto_depIdxs = []int32{
	3, // 0: eos.console.RecycleProto.ls:type_name -> eos.console.RecycleProto.LsProto
	4, // 1: eos.console.RecycleProto.purge:type_name -> eos.console.RecycleProto.PurgeProto
	5, // 2: eos.console.RecycleProto.restore:type_name -> eos.console.RecycleProto.RestoreProto
	6, // 3: eos.console.RecycleProto.config:type_name -> eos.console.RecycleProto.ConfigProto
	7, // 4: eos.console.RecycleProto.project:type_name -> eos.console.RecycleProto.ProjectProto
	0, // 5: eos.console.RecycleProto.LsProto.Type:type_name -> eos.console.RecycleProto.RecycleType
	0, // 6: eos.console.RecycleProto.PurgeProto.Type:type_name -> eos.console.RecycleProto.RecycleType
	1, // 7: eos.console.RecycleProto.ConfigProto.op:type_name -> eos.console.RecycleProto.ConfigProto.OpType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_Recycle_proto_init() }
func file_Recycle_proto_init() {
	if File_Recycle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Recycle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecycleProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recycle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecycleProto_LsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recycle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecycleProto_PurgeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recycle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecycleProto_RestoreProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recycle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecycleProto_ConfigProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recycle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecycleProto_ProjectProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Recycle_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RecycleProto_Ls)(nil),
		(*RecycleProto_Purge)(nil),
		(*RecycleProto_Restore)(nil),
		(*RecycleProto_Config)(nil),
		(*RecycleProto_Project)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Recycle_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Recycle_proto_goTypes,
		DependencyIndexes: file_Recycle_proto_depIdxs,
		EnumInfos:         file_Recycle_proto_enumTypes,
		MessageInfos:      file_Recycle_proto_msgTypes,
	}.Build()
	File_Recycle_proto = out.File
	file_Recycle_proto_rawDesc = nil
	file_Recycle_proto_goTypes = nil
	file_Recycle_proto_depIdxs = nil
}
