// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: Sched.proto

package go_eosgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedProto_ShowProto_Option int32

const (
	SchedProto_ShowProto_TYPE  SchedProto_ShowProto_Option = 0
	SchedProto_ShowProto_STATE SchedProto_ShowProto_Option = 1
)

// Enum value maps for SchedProto_ShowProto_Option.
var (
	SchedProto_ShowProto_Option_name = map[int32]string{
		0: "TYPE",
		1: "STATE",
	}
	SchedProto_ShowProto_Option_value = map[string]int32{
		"TYPE":  0,
		"STATE": 1,
	}
)

func (x SchedProto_ShowProto_Option) Enum() *SchedProto_ShowProto_Option {
	p := new(SchedProto_ShowProto_Option)
	*p = x
	return p
}

func (x SchedProto_ShowProto_Option) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedProto_ShowProto_Option) Descriptor() protoreflect.EnumDescriptor {
	return file_Sched_proto_enumTypes[0].Descriptor()
}

func (SchedProto_ShowProto_Option) Type() protoreflect.EnumType {
	return &file_Sched_proto_enumTypes[0]
}

func (x SchedProto_ShowProto_Option) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedProto_ShowProto_Option.Descriptor instead.
func (SchedProto_ShowProto_Option) EnumDescriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 2, 0}
}

type SchedProto_DisabledProto_Op int32

const (
	SchedProto_DisabledProto_ADD SchedProto_DisabledProto_Op = 0
	SchedProto_DisabledProto_RM  SchedProto_DisabledProto_Op = 1
	SchedProto_DisabledProto_LS  SchedProto_DisabledProto_Op = 2
)

// Enum value maps for SchedProto_DisabledProto_Op.
var (
	SchedProto_DisabledProto_Op_name = map[int32]string{
		0: "ADD",
		1: "RM",
		2: "LS",
	}
	SchedProto_DisabledProto_Op_value = map[string]int32{
		"ADD": 0,
		"RM":  1,
		"LS":  2,
	}
)

func (x SchedProto_DisabledProto_Op) Enum() *SchedProto_DisabledProto_Op {
	p := new(SchedProto_DisabledProto_Op)
	*p = x
	return p
}

func (x SchedProto_DisabledProto_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedProto_DisabledProto_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_Sched_proto_enumTypes[1].Descriptor()
}

func (SchedProto_DisabledProto_Op) Type() protoreflect.EnumType {
	return &file_Sched_proto_enumTypes[1]
}

func (x SchedProto_DisabledProto_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedProto_DisabledProto_Op.Descriptor instead.
func (SchedProto_DisabledProto_Op) EnumDescriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 4, 0}
}

type SchedProto_LsProto_Option int32

const (
	SchedProto_LsProto_BUCKET SchedProto_LsProto_Option = 0
	SchedProto_LsProto_DISK   SchedProto_LsProto_Option = 1
	SchedProto_LsProto_ALL    SchedProto_LsProto_Option = 2
)

// Enum value maps for SchedProto_LsProto_Option.
var (
	SchedProto_LsProto_Option_name = map[int32]string{
		0: "BUCKET",
		1: "DISK",
		2: "ALL",
	}
	SchedProto_LsProto_Option_value = map[string]int32{
		"BUCKET": 0,
		"DISK":   1,
		"ALL":    2,
	}
)

func (x SchedProto_LsProto_Option) Enum() *SchedProto_LsProto_Option {
	p := new(SchedProto_LsProto_Option)
	*p = x
	return p
}

func (x SchedProto_LsProto_Option) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedProto_LsProto_Option) Descriptor() protoreflect.EnumDescriptor {
	return file_Sched_proto_enumTypes[2].Descriptor()
}

func (SchedProto_LsProto_Option) Type() protoreflect.EnumType {
	return &file_Sched_proto_enumTypes[2]
}

func (x SchedProto_LsProto_Option) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedProto_LsProto_Option.Descriptor instead.
func (SchedProto_LsProto_Option) EnumDescriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 6, 0}
}

type SchedProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Subcmd:
	//
	//	*SchedProto_Config
	//	*SchedProto_Ls
	//	*SchedProto_Disabled
	Subcmd isSchedProto_Subcmd `protobuf_oneof:"subcmd"`
}

func (x *SchedProto) Reset() {
	*x = SchedProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sched_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedProto) ProtoMessage() {}

func (x *SchedProto) ProtoReflect() protoreflect.Message {
	mi := &file_Sched_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedProto.ProtoReflect.Descriptor instead.
func (*SchedProto) Descriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0}
}

func (m *SchedProto) GetSubcmd() isSchedProto_Subcmd {
	if m != nil {
		return m.Subcmd
	}
	return nil
}

func (x *SchedProto) GetConfig() *SchedProto_ConfigureProto {
	if x, ok := x.GetSubcmd().(*SchedProto_Config); ok {
		return x.Config
	}
	return nil
}

func (x *SchedProto) GetLs() *SchedProto_LsProto {
	if x, ok := x.GetSubcmd().(*SchedProto_Ls); ok {
		return x.Ls
	}
	return nil
}

func (x *SchedProto) GetDisabled() *SchedProto_DisabledProto {
	if x, ok := x.GetSubcmd().(*SchedProto_Disabled); ok {
		return x.Disabled
	}
	return nil
}

type isSchedProto_Subcmd interface {
	isSchedProto_Subcmd()
}

type SchedProto_Config struct {
	Config *SchedProto_ConfigureProto `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type SchedProto_Ls struct {
	Ls *SchedProto_LsProto `protobuf:"bytes,2,opt,name=ls,proto3,oneof"`
}

type SchedProto_Disabled struct {
	Disabled *SchedProto_DisabledProto `protobuf:"bytes,3,opt,name=disabled,proto3,oneof"`
}

func (*SchedProto_Config) isSchedProto_Subcmd() {}

func (*SchedProto_Ls) isSchedProto_Subcmd() {}

func (*SchedProto_Disabled) isSchedProto_Subcmd() {}

type SchedProto_TypeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This could be an enum like PlacementStrategyT; but every time we
	// introduce a new scheduler, we'd have to modify the cli instead of just
	// parsing on the server side
	Schedtype string `protobuf:"bytes,1,opt,name=schedtype,proto3" json:"schedtype,omitempty"`
}

func (x *SchedProto_TypeProto) Reset() {
	*x = SchedProto_TypeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sched_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedProto_TypeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedProto_TypeProto) ProtoMessage() {}

func (x *SchedProto_TypeProto) ProtoReflect() protoreflect.Message {
	mi := &file_Sched_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedProto_TypeProto.ProtoReflect.Descriptor instead.
func (*SchedProto_TypeProto) Descriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SchedProto_TypeProto) GetSchedtype() string {
	if x != nil {
		return x.Schedtype
	}
	return ""
}

type SchedProto_WeightProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"zigzag32,1,opt,name=id,proto3" json:"id,omitempty"`
	Weight    uint32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Spacename string `protobuf:"bytes,3,opt,name=spacename,proto3" json:"spacename,omitempty"`
}

func (x *SchedProto_WeightProto) Reset() {
	*x = SchedProto_WeightProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sched_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedProto_WeightProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedProto_WeightProto) ProtoMessage() {}

func (x *SchedProto_WeightProto) ProtoReflect() protoreflect.Message {
	mi := &file_Sched_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedProto_WeightProto.ProtoReflect.Descriptor instead.
func (*SchedProto_WeightProto) Descriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SchedProto_WeightProto) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SchedProto_WeightProto) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SchedProto_WeightProto) GetSpacename() string {
	if x != nil {
		return x.Spacename
	}
	return ""
}

type SchedProto_ShowProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option    SchedProto_ShowProto_Option `protobuf:"varint,1,opt,name=option,proto3,enum=eos.console.SchedProto_ShowProto_Option" json:"option,omitempty"`
	Spacename string                      `protobuf:"bytes,2,opt,name=spacename,proto3" json:"spacename,omitempty"`
}

func (x *SchedProto_ShowProto) Reset() {
	*x = SchedProto_ShowProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sched_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedProto_ShowProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedProto_ShowProto) ProtoMessage() {}

func (x *SchedProto_ShowProto) ProtoReflect() protoreflect.Message {
	mi := &file_Sched_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedProto_ShowProto.ProtoReflect.Descriptor instead.
func (*SchedProto_ShowProto) Descriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SchedProto_ShowProto) GetOption() SchedProto_ShowProto_Option {
	if x != nil {
		return x.Option
	}
	return SchedProto_ShowProto_TYPE
}

func (x *SchedProto_ShowProto) GetSpacename() string {
	if x != nil {
		return x.Spacename
	}
	return ""
}

type SchedProto_RefreshProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SchedProto_RefreshProto) Reset() {
	*x = SchedProto_RefreshProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sched_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedProto_RefreshProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedProto_RefreshProto) ProtoMessage() {}

func (x *SchedProto_RefreshProto) ProtoReflect() protoreflect.Message {
	mi := &file_Sched_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedProto_RefreshProto.ProtoReflect.Descriptor instead.
func (*SchedProto_RefreshProto) Descriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 3}
}

type SchedProto_DisabledProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op        SchedProto_DisabledProto_Op `protobuf:"varint,1,opt,name=op,proto3,enum=eos.console.SchedProto_DisabledProto_Op" json:"op,omitempty"`
	Spacename string                      `protobuf:"bytes,2,opt,name=spacename,proto3" json:"spacename,omitempty"`
	Geotag    string                      `protobuf:"bytes,3,opt,name=geotag,proto3" json:"geotag,omitempty"`
	// Operations to deny below the branch. The legacy "plct", "access" and
	// "all" are kept as aliases of the wider grammar the MGM parses, see
	// eos::mgm::placement::ParseDeniedSpec. Empty means "all".
	Spec string `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *SchedProto_DisabledProto) Reset() {
	*x = SchedProto_DisabledProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sched_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedProto_DisabledProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedProto_DisabledProto) ProtoMessage() {}

func (x *SchedProto_DisabledProto) ProtoReflect() protoreflect.Message {
	mi := &file_Sched_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedProto_DisabledProto.ProtoReflect.Descriptor instead.
func (*SchedProto_DisabledProto) Descriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 4}
}

func (x *SchedProto_DisabledProto) GetOp() SchedProto_DisabledProto_Op {
	if x != nil {
		return x.Op
	}
	return SchedProto_DisabledProto_ADD
}

func (x *SchedProto_DisabledProto) GetSpacename() string {
	if x != nil {
		return x.Spacename
	}
	return ""
}

func (x *SchedProto_DisabledProto) GetGeotag() string {
	if x != nil {
		return x.Geotag
	}
	return ""
}

func (x *SchedProto_DisabledProto) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

type SchedProto_ConfigureProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Subopt:
	//
	//	*SchedProto_ConfigureProto_Type
	//	*SchedProto_ConfigureProto_Weight
	//	*SchedProto_ConfigureProto_Show
	//	*SchedProto_ConfigureProto_Refresh
	Subopt isSchedProto_ConfigureProto_Subopt `protobuf_oneof:"subopt"`
}

func (x *SchedProto_ConfigureProto) Reset() {
	*x = SchedProto_ConfigureProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sched_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedProto_ConfigureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedProto_ConfigureProto) ProtoMessage() {}

func (x *SchedProto_ConfigureProto) ProtoReflect() protoreflect.Message {
	mi := &file_Sched_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedProto_ConfigureProto.ProtoReflect.Descriptor instead.
func (*SchedProto_ConfigureProto) Descriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 5}
}

func (m *SchedProto_ConfigureProto) GetSubopt() isSchedProto_ConfigureProto_Subopt {
	if m != nil {
		return m.Subopt
	}
	return nil
}

func (x *SchedProto_ConfigureProto) GetType() *SchedProto_TypeProto {
	if x, ok := x.GetSubopt().(*SchedProto_ConfigureProto_Type); ok {
		return x.Type
	}
	return nil
}

func (x *SchedProto_ConfigureProto) GetWeight() *SchedProto_WeightProto {
	if x, ok := x.GetSubopt().(*SchedProto_ConfigureProto_Weight); ok {
		return x.Weight
	}
	return nil
}

func (x *SchedProto_ConfigureProto) GetShow() *SchedProto_ShowProto {
	if x, ok := x.GetSubopt().(*SchedProto_ConfigureProto_Show); ok {
		return x.Show
	}
	return nil
}

func (x *SchedProto_ConfigureProto) GetRefresh() *SchedProto_RefreshProto {
	if x, ok := x.GetSubopt().(*SchedProto_ConfigureProto_Refresh); ok {
		return x.Refresh
	}
	return nil
}

type isSchedProto_ConfigureProto_Subopt interface {
	isSchedProto_ConfigureProto_Subopt()
}

type SchedProto_ConfigureProto_Type struct {
	Type *SchedProto_TypeProto `protobuf:"bytes,1,opt,name=type,proto3,oneof"`
}

type SchedProto_ConfigureProto_Weight struct {
	Weight *SchedProto_WeightProto `protobuf:"bytes,2,opt,name=weight,proto3,oneof"`
}

type SchedProto_ConfigureProto_Show struct {
	Show *SchedProto_ShowProto `protobuf:"bytes,3,opt,name=show,proto3,oneof"`
}

type SchedProto_ConfigureProto_Refresh struct {
	Refresh *SchedProto_RefreshProto `protobuf:"bytes,4,opt,name=refresh,proto3,oneof"`
}

func (*SchedProto_ConfigureProto_Type) isSchedProto_ConfigureProto_Subopt() {}

func (*SchedProto_ConfigureProto_Weight) isSchedProto_ConfigureProto_Subopt() {}

func (*SchedProto_ConfigureProto_Show) isSchedProto_ConfigureProto_Subopt() {}

func (*SchedProto_ConfigureProto_Refresh) isSchedProto_ConfigureProto_Subopt() {}

type SchedProto_LsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option    SchedProto_LsProto_Option `protobuf:"varint,1,opt,name=option,proto3,enum=eos.console.SchedProto_LsProto_Option" json:"option,omitempty"`
	Spacename string                    `protobuf:"bytes,2,opt,name=spacename,proto3" json:"spacename,omitempty"`
}

func (x *SchedProto_LsProto) Reset() {
	*x = SchedProto_LsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sched_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedProto_LsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedProto_LsProto) ProtoMessage() {}

func (x *SchedProto_LsProto) ProtoReflect() protoreflect.Message {
	mi := &file_Sched_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedProto_LsProto.ProtoReflect.Descriptor instead.
func (*SchedProto_LsProto) Descriptor() ([]byte, []int) {
	return file_Sched_proto_rawDescGZIP(), []int{0, 6}
}

func (x *SchedProto_LsProto) GetOption() SchedProto_LsProto_Option {
	if x != nil {
		return x.Option
	}
	return SchedProto_LsProto_BUCKET
}

func (x *SchedProto_LsProto) GetSpacename() string {
	if x != nil {
		return x.Spacename
	}
	return ""
}

var File_Sched_proto protoreflect.FileDescriptor

var file_Sched_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x53, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65,
	0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x22, 0xcb, 0x08, 0x0a, 0x0a, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x40, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65, 0x6f, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x31, 0x0a, 0x02, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4c, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x02, 0x6c, 0x73, 0x12, 0x43,
	0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x1a, 0x29, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x53,
	0x0a, 0x0b, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x1a, 0x8a, 0x01, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x40, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x28, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x1d, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x54,
	0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x01,
	0x1a, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0xb8, 0x01, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x38, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28,
	0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65,
	0x6f, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6f, 0x74,
	0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x1d, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x07, 0x0a, 0x03,
	0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x52, 0x4d, 0x10, 0x01, 0x12, 0x06, 0x0a,
	0x02, 0x4c, 0x53, 0x10, 0x02, 0x4a, 0x04, 0x08, 0x04, 0x10, 0x05, 0x1a, 0x8d, 0x02, 0x0a, 0x0e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x37,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x65,
	0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48,
	0x00, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x37, 0x0a, 0x04, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68,
	0x6f, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x73, 0x68, 0x6f, 0x77, 0x12,
	0x40, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6f, 0x70, 0x74, 0x1a, 0x90, 0x01, 0x0a, 0x07,
	0x4c, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3e, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4c, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0a, 0x0a, 0x06, 0x42, 0x55, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44,
	0x49, 0x53, 0x4b, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x42, 0x08,
	0x0a, 0x06, 0x73, 0x75, 0x62, 0x63, 0x6d, 0x64, 0x42, 0x8a, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d,
	0x2e, 0x65, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x42, 0x0a, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x72, 0x6e, 0x2d, 0x65, 0x6f, 0x73, 0x2f,
	0x67, 0x6f, 0x2d, 0x65, 0x6f, 0x73, 0x67, 0x72, 0x70, 0x63, 0xa2, 0x02, 0x03, 0x45, 0x43, 0x58,
	0xaa, 0x02, 0x0b, 0x45, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0xca, 0x02,
	0x0b, 0x45, 0x6f, 0x73, 0x5c, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0xe2, 0x02, 0x17, 0x45,
	0x6f, 0x73, 0x5c, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x45, 0x6f, 0x73, 0x3a, 0x3a, 0x43, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Sched_proto_rawDescOnce sync.Once
	file_Sched_proto_rawDescData = file_Sched_proto_rawDesc
)

func file_Sched_proto_rawDescGZIP() []byte {
	file_Sched_proto_rawDescOnce.Do(func() {
		file_Sched_proto_rawDescData = protoimpl.X.CompressGZIP(file_Sched_proto_rawDescData)
	})
	return file_Sched_proto_rawDescData
}

var file_Sched_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Sched_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Sched_proto_goTypes = []interface{}{
	(SchedProto_ShowProto_Option)(0),  // 0: eos.console.SchedProto.ShowProto.Option
	(SchedProto_DisabledProto_Op)(0),  // 1: eos.console.SchedProto.DisabledProto.Op
	(SchedProto_LsProto_Option)(0),    // 2: eos.console.SchedProto.LsProto.Option
	(*SchedProto)(nil),                // 3: eos.console.SchedProto
	(*SchedProto_TypeProto)(nil),      // 4: eos.console.SchedProto.TypeProto
	(*SchedProto_WeightProto)(nil),    // 5: eos.console.SchedProto.WeightProto
	(*SchedProto_ShowProto)(nil),      // 6: eos.console.SchedProto.ShowProto
	(*SchedProto_RefreshProto)(nil),   // 7: eos.console.SchedProto.RefreshProto
	(*SchedProto_DisabledProto)(nil),  // 8: eos.console.SchedProto.DisabledProto
	(*SchedProto_ConfigureProto)(nil), // 9: eos.console.SchedProto.ConfigureProto
	(*SchedProto_LsProto)(nil),        // 10: eos.console.SchedProto.LsProto
}
var file_Sched_proto_depIdxs = []int32{
	9,  // 0: eos.console.SchedProto.config:type_name -> eos.console.SchedProto.ConfigureProto
	10, // 1: eos.console.SchedProto.ls:type_name -> eos.console.SchedProto.LsProto
	8,  // 2: eos.console.SchedProto.disabled:type_name -> eos.console.SchedProto.DisabledProto
	0,  // 3: eos.console.SchedProto.ShowProto.option:type_name -> eos.console.SchedProto.ShowProto.Option
	1,  // 4: eos.console.SchedProto.DisabledProto.op:type_name -> eos.console.SchedProto.DisabledProto.Op
	4,  // 5: eos.console.SchedProto.ConfigureProto.type:type_name -> eos.console.SchedProto.TypeProto
	5,  // 6: eos.console.SchedProto.ConfigureProto.weight:type_name -> eos.console.SchedProto.WeightProto
	6,  // 7: eos.console.SchedProto.ConfigureProto.show:type_name -> eos.console.SchedProto.ShowProto
	7,  // 8: eos.console.SchedProto.ConfigureProto.refresh:type_name -> eos.console.SchedProto.RefreshProto
	2,  // 9: eos.console.SchedProto.LsProto.option:type_name -> eos.console.SchedProto.LsProto.Option
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_Sched_proto_init() }
func file_Sched_proto_init() {
	if File_Sched_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Sched_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Sched_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedProto_TypeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Sched_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedProto_WeightProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Sched_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedProto_ShowProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Sched_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedProto_RefreshProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Sched_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedProto_DisabledProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Sched_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedProto_ConfigureProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Sched_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedProto_LsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Sched_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SchedProto_Config)(nil),
		(*SchedProto_Ls)(nil),
		(*SchedProto_Disabled)(nil),
	}
	file_Sched_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*SchedProto_ConfigureProto_Type)(nil),
		(*SchedProto_ConfigureProto_Weight)(nil),
		(*SchedProto_ConfigureProto_Show)(nil),
		(*SchedProto_ConfigureProto_Refresh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Sched_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Sched_proto_goTypes,
		DependencyIndexes: file_Sched_proto_depIdxs,
		EnumInfos:         file_Sched_proto_enumTypes,
		MessageInfos:      file_Sched_proto_msgTypes,
	}.Build()
	File_Sched_proto = out.File
	file_Sched_proto_rawDesc = nil
	file_Sched_proto_goTypes = nil
	file_Sched_proto_depIdxs = nil
}
