// ----------------------------------------------------------------------------
// File: TrafficShaping.proto
// Author: Luis Antonio Obis Aparicio <luis.obis@cern.ch>
// ----------------------------------------------------------------------------

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: TrafficShaping.proto

package go_eosgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TrafficShapingService_StreamIoStats_FullMethodName = "/eos.traffic_shaping.TrafficShapingService/StreamIoStats"
)

// TrafficShapingServiceClient is the client API for TrafficShapingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficShapingServiceClient interface {
	// Bidirectional streaming: The FST opens a stream and pushes FstIoReport repeatedly.
	// The MGM can push back MgmIoResponse (limits/acks) asynchronously.
	StreamIoStats(ctx context.Context, opts ...grpc.CallOption) (TrafficShapingService_StreamIoStatsClient, error)
}

type trafficShapingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficShapingServiceClient(cc grpc.ClientConnInterface) TrafficShapingServiceClient {
	return &trafficShapingServiceClient{cc}
}

func (c *trafficShapingServiceClient) StreamIoStats(ctx context.Context, opts ...grpc.CallOption) (TrafficShapingService_StreamIoStatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TrafficShapingService_ServiceDesc.Streams[0], TrafficShapingService_StreamIoStats_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &trafficShapingServiceStreamIoStatsClient{stream}
	return x, nil
}

type TrafficShapingService_StreamIoStatsClient interface {
	Send(*FstIoReport) error
	Recv() (*MgmIoResponse, error)
	grpc.ClientStream
}

type trafficShapingServiceStreamIoStatsClient struct {
	grpc.ClientStream
}

func (x *trafficShapingServiceStreamIoStatsClient) Send(m *FstIoReport) error {
	return x.ClientStream.SendMsg(m)
}

func (x *trafficShapingServiceStreamIoStatsClient) Recv() (*MgmIoResponse, error) {
	m := new(MgmIoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrafficShapingServiceServer is the server API for TrafficShapingService service.
// All implementations should embed UnimplementedTrafficShapingServiceServer
// for forward compatibility
type TrafficShapingServiceServer interface {
	// Bidirectional streaming: The FST opens a stream and pushes FstIoReport repeatedly.
	// The MGM can push back MgmIoResponse (limits/acks) asynchronously.
	StreamIoStats(TrafficShapingService_StreamIoStatsServer) error
}

// UnimplementedTrafficShapingServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTrafficShapingServiceServer struct {
}

func (UnimplementedTrafficShapingServiceServer) StreamIoStats(TrafficShapingService_StreamIoStatsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamIoStats not implemented")
}

// UnsafeTrafficShapingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficShapingServiceServer will
// result in compilation errors.
type UnsafeTrafficShapingServiceServer interface {
	mustEmbedUnimplementedTrafficShapingServiceServer()
}

func RegisterTrafficShapingServiceServer(s grpc.ServiceRegistrar, srv TrafficShapingServiceServer) {
	s.RegisterService(&TrafficShapingService_ServiceDesc, srv)
}

func _TrafficShapingService_StreamIoStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrafficShapingServiceServer).StreamIoStats(&trafficShapingServiceStreamIoStatsServer{stream})
}

type TrafficShapingService_StreamIoStatsServer interface {
	Send(*MgmIoResponse) error
	Recv() (*FstIoReport, error)
	grpc.ServerStream
}

type trafficShapingServiceStreamIoStatsServer struct {
	grpc.ServerStream
}

func (x *trafficShapingServiceStreamIoStatsServer) Send(m *MgmIoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *trafficShapingServiceStreamIoStatsServer) Recv() (*FstIoReport, error) {
	m := new(FstIoReport)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrafficShapingService_ServiceDesc is the grpc.ServiceDesc for TrafficShapingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficShapingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eos.traffic_shaping.TrafficShapingService",
	HandlerType: (*TrafficShapingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIoStats",
			Handler:       _TrafficShapingService_StreamIoStats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "TrafficShaping.proto",
}
